add yarn lock
[kushal@ideapadflex-kushal npmjs]$ git clone https://github.com/kusl/kush kush
Cloning into 'kush'...
remote: Enumerating objects: 19, done.
remote: Total 19 (delta 0), reused 0 (delta 0), pack-reused 19
Unpacking objects: 100% (19/19), 2.78 KiB | 569.00 KiB/s, done.
[kushal@ideapadflex-kushal npmjs]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
[master b817a11] add a readme file
 1 file changed, 7 insertions(+)
 create mode 100644 README.md
From https://github.com/kusl/kush
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
Username for 'https://github.com': ^C
[kushal@ideapadflex-kushal kush]$ git remote remove origin;git remote add origin git@github.com:kusl/kush.git
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
[master 41abef3] add signature
 1 file changed, 1 insertion(+), 1 deletion(-)
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
From github.com:kusl/kush
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
Current branch master is up to date.
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 2.03 KiB | 2.03 MiB/s, done.
Total 6 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), done.
To github.com:kusl/kush.git
   3f12c49..41abef3  master -> master
[kushal@ideapadflex-kushal kush]$ yarn install
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
Aborting commit due to empty commit message.
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
Everything up-to-date
[kushal@ideapadflex-kushal kush]$ vim .gitignore
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
Aborting commit due to empty commit message.
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
Everything up-to-date
[kushal@ideapadflex-kushal kush]$ vim .gitignore
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
Aborting commit due to empty commit message.
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
Everything up-to-date
[kushal@ideapadflex-kushal kush]$ git checkout
A	.gitignore
A	node_modules/.yarn-integrity
A	yarn.lock
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

[kushal@ideapadflex-kushal kush]$ vim .gitignore
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitignore

[kushal@ideapadflex-kushal kush]$ git checkout .
Updated 1 path from the index
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

[kushal@ideapadflex-kushal kush]$ vim .gitignore
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitignore

[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitignore

[kushal@ideapadflex-kushal kush]$ git checkout .
Updated 1 path from the index
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

[kushal@ideapadflex-kushal kush]$ code -r .
[kushal@ideapadflex-kushal kush]$