use yarn 2
[kushal@ideapadflex-kushal src]$ mkdir npmjs
[kushal@ideapadflex-kushal src]$ cd npmjs/
[kushal@ideapadflex-kushal npmjs]$ git clone https://github.com/kusl/kush kush
Cloning into 'kush'...
remote: Enumerating objects: 19, done.
remote: Total 19 (delta 0), reused 0 (delta 0), pack-reused 19
Unpacking objects: 100% (19/19), 2.78 KiB | 569.00 KiB/s, done.
[kushal@ideapadflex-kushal npmjs]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
[master b817a11] add a readme file
 1 file changed, 7 insertions(+)
 create mode 100644 README.md
From https://github.com/kusl/kush
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
Username for 'https://github.com': ^C
[kushal@ideapadflex-kushal kush]$ git remote remove origin;git remote add origin git@github.com:kusl/kush.git
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
[master 41abef3] add signature
 1 file changed, 1 insertion(+), 1 deletion(-)
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
From github.com:kusl/kush
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
Current branch master is up to date.
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 2.03 KiB | 2.03 MiB/s, done.
Total 6 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), done.
To github.com:kusl/kush.git
   3f12c49..41abef3  master -> master
[kushal@ideapadflex-kushal kush]$ yarn install
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
Aborting commit due to empty commit message.
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
Everything up-to-date
[kushal@ideapadflex-kushal kush]$ vim .gitignore
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
Aborting commit due to empty commit message.
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
Everything up-to-date
[kushal@ideapadflex-kushal kush]$ vim .gitignore
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
Aborting commit due to empty commit message.
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
Everything up-to-date
[kushal@ideapadflex-kushal kush]$ git checkout
A	.gitignore
A	node_modules/.yarn-integrity
A	yarn.lock
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

[kushal@ideapadflex-kushal kush]$ vim .gitignore
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitignore

[kushal@ideapadflex-kushal kush]$ git checkout .
Updated 1 path from the index
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

[kushal@ideapadflex-kushal kush]$ vim .gitignore
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitignore

[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitignore

[kushal@ideapadflex-kushal kush]$ git checkout .
Updated 1 path from the index
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

[kushal@ideapadflex-kushal kush]$ code -r .
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
[master f8ee882] ignore package lock json
 1 file changed, 1 insertion(+)
From github.com:kusl/kush
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.02 KiB | 1.02 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:kusl/kush.git
   e570b7d..f8ee882  master -> master
[kushal@ideapadflex-kushal kush]$ yarn run test
yarn run v1.22.4
$ node index.js
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ yarn run test
yarn run v1.22.4
$ node index.js
/home/kushal/src/npmjs/kush/index.js:1
const extraInformation;
      ^^^^^^^^^^^^^^^^

SyntaxError: Missing initializer in const declaration
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[kushal@ideapadflex-kushal kush]$ yarn run test
yarn run v1.22.4
$ node index.js
(node:19644) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/home/kushal/src/npmjs/kush/index.js:9
export default function(info) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[kushal@ideapadflex-kushal kush]$ yarn run test kushal
yarn run v1.22.4
$ node index.js kushal
Done in 0.10s.
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld()
bash: syntax error near unexpected token `('
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ node index.js
[kushal@ideapadflex-kushal kush]$ node index.js
hello world
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
hello world
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
hi
Done in 0.12s.
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
Hello potato, undefined
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
Hello potato, tomato
Done in 0.12s.
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
[master 9a7b4f8] run some experiments
 1 file changed, 5 insertions(+), 2 deletions(-)
From github.com:kusl/kush
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 2.84 KiB | 2.84 MiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:kusl/kush.git
   f8ee882..9a7b4f8  master -> master
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
[master 09908a5] revert experiments
 1 file changed, 2 insertions(+), 5 deletions(-)
From github.com:kusl/kush
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1001 bytes | 1001.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:kusl/kush.git
   9a7b4f8..09908a5  master -> master
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
From github.com:kusl/kush
 * branch            master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
Everything up-to-date
[kushal@ideapadflex-kushal kush]$ yarn npm publish
yarn run v1.22.4
error Command "npm" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[kushal@ideapadflex-kushal kush]$ yarn policies set-version berry
Resolving berry to a url...
Downloading https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js...
Saving it into /home/kushal/src/npmjs/kush/.yarn/releases/yarn-berry.js...
Updating /home/kushal/src/npmjs/kush/.yarnrc.yml...
Done!
[kushal@ideapadflex-kushal kush]$ yarn npm publish
Internal Error: kush@workspace:.: This package doesn't seem to be present in your lockfile; try to make an install to update your resolutions
    at t.RunInstallPleaseResolver.getCandidates (/home/kushal/src/npmjs/kush/.yarn/releases/yarn-berry.js:28:868636)
    at t.MultiResolver.getCandidates (/home/kushal/src/npmjs/kush/.yarn/releases/yarn-berry.js:16:42854)
    at /home/kushal/src/npmjs/kush/.yarn/releases/yarn-berry.js:28:586263
    at /home/kushal/src/npmjs/kush/.yarn/releases/yarn-berry.js:28:864071
    at new Promise (<anonymous>)
    at e.exports (/home/kushal/src/npmjs/kush/.yarn/releases/yarn-berry.js:28:864053)
    at i (/home/kushal/src/npmjs/kush/.yarn/releases/yarn-berry.js:28:863748)
    at /home/kushal/src/npmjs/kush/.yarn/releases/yarn-berry.js:28:863821
    at /home/kushal/src/npmjs/kush/.yarn/releases/yarn-berry.js:28:863864
    at new Promise (<anonymous>)
[kushal@ideapadflex-kushal kush]$ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0.01s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s
➤ YN0000: ┌ Link step
➤ YN0031: │ One or more node_modules have been detected and will be removed. This operation may take some time.
➤ YN0000: └ Completed in 0.02s
➤ YN0000: Done with warnings in 0.03s
[kushal@ideapadflex-kushal kush]$