run some experiments
[kushal@ideapadflex-kushal src]$ mkdir npmjs
[kushal@ideapadflex-kushal src]$ cd npmjs/
[kushal@ideapadflex-kushal npmjs]$ git clone https://github.com/kusl/kush kush
Cloning into 'kush'...
remote: Enumerating objects: 19, done.
remote: Total 19 (delta 0), reused 0 (delta 0), pack-reused 19
Unpacking objects: 100% (19/19), 2.78 KiB | 569.00 KiB/s, done.
[kushal@ideapadflex-kushal npmjs]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
[master b817a11] add a readme file
 1 file changed, 7 insertions(+)
 create mode 100644 README.md
From https://github.com/kusl/kush
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
Username for 'https://github.com': ^C
[kushal@ideapadflex-kushal kush]$ git remote remove origin;git remote add origin git@github.com:kusl/kush.git
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
[master 41abef3] add signature
 1 file changed, 1 insertion(+), 1 deletion(-)
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
From github.com:kusl/kush
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
Current branch master is up to date.
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 2.03 KiB | 2.03 MiB/s, done.
Total 6 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), done.
To github.com:kusl/kush.git
   3f12c49..41abef3  master -> master
[kushal@ideapadflex-kushal kush]$ yarn install
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
Aborting commit due to empty commit message.
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
Everything up-to-date
[kushal@ideapadflex-kushal kush]$ vim .gitignore
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
Aborting commit due to empty commit message.
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
Everything up-to-date
[kushal@ideapadflex-kushal kush]$ vim .gitignore
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
Aborting commit due to empty commit message.
error: cannot pull with rebase: Your index contains uncommitted changes.
error: please commit or stash them.
Everything up-to-date
[kushal@ideapadflex-kushal kush]$ git checkout
A	.gitignore
A	node_modules/.yarn-integrity
A	yarn.lock
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

[kushal@ideapadflex-kushal kush]$ vim .gitignore
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitignore

[kushal@ideapadflex-kushal kush]$ git checkout .
Updated 1 path from the index
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

[kushal@ideapadflex-kushal kush]$ vim .gitignore
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitignore

[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitignore

[kushal@ideapadflex-kushal kush]$ git checkout .
Updated 1 path from the index
[kushal@ideapadflex-kushal kush]$ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   .gitignore
	new file:   node_modules/.yarn-integrity
	new file:   yarn.lock

[kushal@ideapadflex-kushal kush]$ code -r .
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master
[master f8ee882] ignore package lock json
 1 file changed, 1 insertion(+)
From github.com:kusl/kush
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.02 KiB | 1.02 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:kusl/kush.git
   e570b7d..f8ee882  master -> master
[kushal@ideapadflex-kushal kush]$ yarn run test
yarn run v1.22.4
$ node index.js
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ yarn run test
yarn run v1.22.4
$ node index.js
/home/kushal/src/npmjs/kush/index.js:1
const extraInformation;
      ^^^^^^^^^^^^^^^^

SyntaxError: Missing initializer in const declaration
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[kushal@ideapadflex-kushal kush]$ yarn run test
yarn run v1.22.4
$ node index.js
(node:19644) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/home/kushal/src/npmjs/kush/index.js:9
export default function(info) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[kushal@ideapadflex-kushal kush]$ yarn run test kushal
yarn run v1.22.4
$ node index.js kushal
Done in 0.10s.
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld()
bash: syntax error near unexpected token `('
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ node index.js
[kushal@ideapadflex-kushal kush]$ node index.js
hello world
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
hello world
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
hi
Done in 0.12s.
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
Hello potato, undefined
Done in 0.11s.
[kushal@ideapadflex-kushal kush]$ yarn run test helloWorld
yarn run v1.22.4
$ node index.js helloWorld
Hello potato, tomato
Done in 0.12s.
[kushal@ideapadflex-kushal kush]$ cd ~/src/npmjs/kush/;vim README.md;git add .;git commit;git pull -r origin master;git push origin master